#!/usr/bin/env bash
# Generated by scripts/build_setup.py; edit setup-launcher.sh.in instead.
set -euo pipefail
setup_main() {
    local candidate
    local profile='proxmox' readonly=0 yes=0 arg py='' root='' source_path=''
    for arg in "$@"; do
        case "$arg" in --status|--plan|--help|-h) readonly=1 ;; --yes) yes=1 ;; esac
    done
    for candidate in python3 /opt/homebrew/opt/python@3.13/bin/python3.13 /usr/local/opt/python@3.13/bin/python3.13 /opt/homebrew/bin/python3 /usr/local/bin/python3; do
        if command -v "$candidate" >/dev/null 2>&1 && "$candidate" -I -c 'import sys; raise SystemExit(sys.version_info < (3, 11))' 2>/dev/null; then
            py="$candidate"; break
        fi
    done
    if [ -z "$py" ]; then
        echo 'Setup requires Python 3.11+. --status/--plan never install prerequisites.' >&2
        if [ "$readonly" = 1 ]; then
            echo 'Options: --status --plan --yes --only a,b --with-deps --resume RUN_ID --fail-fast --json'
            return 2
        fi
        if [ "$profile" = proxmox ]; then
            echo 'Use the supported Python on your Proxmox host; setup will not replace its interpreter.' >&2; return 2
        fi
        if [ "$yes" != 1 ]; then
            read -r -p 'Install the Python runtime using apt or existing Homebrew? [y/N] ' arg </dev/tty
            case "$arg" in [Yy]*) ;; *) return 2 ;; esac
        fi
        case "$(uname -s)" in
            Linux)
                # shellcheck source=/dev/null
                . /etc/os-release
                [ "${ID:-}" = debian ] && [ "${VERSION_ID:-}" = 13 ] || return 2
                if [ "$(id -u)" = 0 ]; then apt-get update; apt-get install -y python3
                elif command -v sudo >/dev/null; then sudo apt-get update; sudo apt-get install -y python3
                else su -c 'apt-get update && apt-get install -y python3' </dev/tty; fi ;;
            Darwin)
                if command -v brew >/dev/null; then brew install python@3.13
                elif [ -x /opt/homebrew/bin/brew ]; then /opt/homebrew/bin/brew install python@3.13
                else echo 'Install Homebrew and Python 3.11+ first, then rerun setup.' >&2; return 2; fi ;;
            *) return 2 ;;
        esac
        py=python3
        for candidate in /opt/homebrew/opt/python@3.13/bin/python3.13 /usr/local/opt/python@3.13/bin/python3.13; do
            if [ -x "$candidate" ]; then py="$candidate"; break; fi
        done
        "$py" -I -c 'import sys; raise SystemExit(sys.version_info < (3, 11))'
    fi
    # Piped into bash, BASH_SOURCE is "main", not a path: a file of that name in
    # the current directory must never select local code over the release.
    source_path="${BASH_SOURCE[0]:-}"
    if [ -n "$source_path" ] && [ "$source_path" = "$0" ] && [ -f "$source_path" ]; then
        root="$("$py" -I -c 'import pathlib,sys; print(pathlib.Path(sys.argv[1]).resolve().parent.parent)' "$source_path")"
    fi
    if [ -n "$root" ] && [ -f "$root/setup_core/__main__.py" ]; then
        "$py" -I -c 'import sys; sys.path.insert(0,sys.argv.pop(1)); from setup_core.cli import main; raise SystemExit(main())' "$root" --profile "$profile" "$@"
        return
    fi
    local temporary url rc=0
    temporary="$(mktemp -d)"
    # Expanded now: the trap can run after this function's locals are gone.
    # shellcheck disable=SC2064
    trap "rm -rf $(printf %q "$temporary")" EXIT
    url='https://github.com/zxj001/nas_scripts/releases/download/setup-v1.0.0'
    # Fetch complete, version-matched assets; never stream installers into a shell.
    # Read-only runs fetch it too: a verified bundle in a temporary directory
    # installs nothing. A failed fetch or checksum is a bootstrap error (2).
    if ! "$py" -I -c 'import pathlib,sys,urllib.request
base,directory=sys.argv[1:]
for name in ("setup.pyz", "setup.pyz.sha256"):
    try:
        with urllib.request.urlopen(base+"/"+name, timeout=120) as response:
            pathlib.Path(directory,name).write_bytes(response.read())
    except OSError as error: raise SystemExit(name + ": " + str(error))
' "$url" "$temporary" || ! "$py" -I -c 'import hashlib,pathlib,sys
p=pathlib.Path(sys.argv[1]); expected=(p/"setup.pyz.sha256").read_text().split()[0]
if hashlib.sha256((p/"setup.pyz").read_bytes()).hexdigest()!=expected: raise SystemExit("setup checksum mismatch")
' "$temporary"; then
        echo "could not fetch a verified setup-v1.0.0 bundle from $url" >&2
        rm -rf "$temporary"
        trap - EXIT
        return 2
    fi
    "$py" -I "$temporary/setup.pyz" --profile "$profile" "$@" || rc=$?
    rm -rf "$temporary"
    trap - EXIT
    return "$rc"
}
setup_main "$@"
